// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { config } from 'dotenv'
import { defineConfig } from 'prisma/config'

// Next.js는 .env.local을 우선적으로 로드하므로 Prisma CLI에서도 동일하게 처리
config({ path: '.env.local', override: true })

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // 마이그레이션/db push: 직접 연결 사용 (트랜잭션 풀러는 DDL 미지원)
    // 앱 런타임: prisma.ts에서 DATABASE_URL(트랜잭션 풀러) 사용
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
})
